<div class="container-fluid">
    <div class="row">
        <div class="col-m-5" style="text-align:justify;">
            <?php echo __('Thank you very much for downloading Touchize Commerce, a simpler faster and more enjoyable mobile shopping experience!') ?>
            <br>
            <br>
            <?php echo __('Touchize Commerce can help you:') ?>
            <ul>
                <li><?php echo __('Increase your conversion rates')?></li>
                <li><?php echo __('Get more products in the shopping cart')?></li>
                <li><?php echo __('Improve customer loyalty') ?></li>
            </ul>
            <?php echo __('Simply follow these 3 steps to get started with Touchize Commerce    and get an instant view of your Touchified shop. And if you like it, please don’t hesistate to sign up for your 30 day free trial.') ?>
            <ul>
                <li><?php echo __('Choose your template')?></li>
                <li><?php echo __('Choose your banners')?></li>
                <li><?php echo __('Setup your link menu')?></li>
            </ul>
            <strong><?php echo __('Important note')?></strong><br>
            <?php echo __('Touchize Commerce is for mobiles, tablets and other types of touchscreen devices, and does not in any way affect your desktop users shopping experience.')?>
            <br>
        </div>
        <div class="col-m-1">
        </div>
        <div class="col-m-6">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/A3-W6DCIPEk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
        </div>
    </div>
</div>