<link rel="stylesheet" type="text/css" href="https://d2kt9xhiosnf0k.cloudfront.net/touchize/latest/css/slq.css">
<script type="text/javascript" src="<?php echo $block->getPluginUrl()?>"></script>
<div id="sq-base" class=""></div>
<script type="text/javascript">
    window.onload = function() {
        window.slqcore = new Slq.StoreFront(<?php echo $block->getPageConfig() ?>);
        window.slqcore.start("#sq-base");
    };
</script>